### ISSUE TITLE
Main screen (client part)

### ISSUE THREAD

**Issue by AleksMorozova** [AleksMorozova/Gruvo#3]
mockup:  03-лента

**Comment by horba** [comment]
В рамках задачи нужно сделать:

1. Верстка и стили для главной странички - home.component.html и home.component.css
2. home.component.ts - непосредственно компонент, который обеспечивает вьюху необходимыми биндингами.
3. необходимые интерфейсы, например ITweet
4. TweetService - сервис, пока-что содержащий метод getTweets() -который возвращает статичные данные (т.е. просто зашитый внутри массив ITweet, инициализированный каким-то значением)
5. Прописать роутинг для '/home' для вашего компонента.
