### ISSUE TITLE
User profile screen (client part)

### ISSUE THREAD

**Issue by AleksMorozova** [AleksMorozova/Gruvo#5]
mockup:  05-профиль

**Comment by horba** [comment]
В рамках задачи нужно сделать:
1. Верстка и стили для странички профиля пользователя - user-profile.component.html и user-profile.component.css
2. user-profile.component.ts - непосредственно компонент, который обеспечивает вьюху необходимыми биндингами.
3. user.model.ts - содержит интерфейс IUser пользовательских данных и если нужно модель User, юзается в компоненте и сервисе
4. <ServiceName>Service - сервис, пока-что содержащий метод getUserData() -который возвращает статичные данные (т.е. просто зашитый внутри объект IUser, инициализированный каким-то значением)
5. Прописать роутинг для '/user-profile' для вашего компонента.
